In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v1", is_slippery=False)

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.9

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [5]:
rewards_all_episodes=  []

# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table for Q(s,a)
        q_table[state,action] = q_table[state,action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done:
            break
            
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)

In [6]:
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)

********Average reward per thousand episodes********

1000 :  0.2690000000000002
2000 :  0.7430000000000005
3000 :  0.9070000000000007
4000 :  0.9550000000000007
5000 :  0.9730000000000008
6000 :  0.9880000000000008
7000 :  0.9860000000000008
8000 :  0.9910000000000008
9000 :  0.9820000000000008
10000 :  0.9910000000000008


********Q-table********

[[5.31441000e-01 5.90490000e-01 4.78296896e-01 5.31441000e-01]
 [5.31441000e-01 0.00000000e+00 2.98354127e-01 4.41804662e-01]
 [4.30735173e-01 5.41477670e-02 6.73012319e-03 1.01366503e-01]
 [8.22900799e-02 0.00000000e+00 7.05458765e-05 4.79276230e-03]
 [5.90490000e-01 6.56100000e-01 0.00000000e+00 5.31441000e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 6.88867746e-01 0.00000000e+00 5.56046313e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.56100000e-01 0.00000000e+00 7.29000000e-01 5.90490000e-01]
 [6.56099998e-01 8.10000000e-01 8.09999930e-01 0.00000000e+00]
 [6.30222241e-01 9

In [10]:
for episode in range(1):
    state = env.reset()
    done = False
    print("******** EPISODE ", episode+1, "********\n\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("******** You reached the goal! ********")
                time.sleep(3)
            else:
                print("******** You fell through a hole! ********")
                time.sleep(3)
            clear_output(wait=True)
            break
        
        state = new_state

env.close()

  (Right)
SFFF
FHFH
FFFH
HFFG
******** You reached the goal! ********
