In [21]:
import numpy as np
import math
import pandas as pd

# Grid must be a tuple for (rows,cols) sizes of grid
# Reward must be an array of tuples (y,x) where reward is placed
# Punishment must be an array of tuples (y,x) where punishment is placed

class RLearn:
    
    def __init__(self, grid, rewards, punishments, obstacles):
        self.grid = self.create_grid_with_reward_punishment(grid, rewards, punishments, obstacles)
        self.actions = ([0,1], [0,-1], [1,0], [-1,0])
        self.q_table = self.create_q_table((0,0))
    #end

    def create_grid_with_reward_punishment(self, grid, rewards, punishments, obstacles):
        REWARD = 1
        PUNISHMENT = -1
        OBSTACLE = -99
        grid = np.full((grid[0], grid[1]), -0.1)
        for reward in rewards:
            grid[reward[0], reward[1]] = REWARD
        for punishment in punishments:
            grid[punishment[0], punishment[1]] = PUNISHMENT
        for obstacle in obstacles:
            grid[obstacle[0], obstacle[1]] = OBSTACLE
        return grid
    #end
    
    def create_q_table(self, start_position):
        row, col = self.grid.shape
        table = np.zeros((row*col, len(self.actions)))
        return table
    #end
#end

In [22]:
rlearn = RLearn((3,3), [(0,0)], [(1,1)], [(0,2)])
print(rlearn.grid)

[[  1.   -0.1 -99. ]
 [ -0.1  -1.   -0.1]
 [ -0.1  -0.1  -0.1]]


In [23]:
rlearn.create_q_table((0,0))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
exploration_rate = 1
exploration_rate_decay = 0.001