In [1]:
import sys

In [2]:
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install gym

In [5]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output
from gym.envs.toy_text.frozen_lake import generate_random_map


In [7]:
env = gym.make("FrozenLake-v1")
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
num_episodes = 20000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.90

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [10]:
rewards_all_episodes = []

# Q-Learning algorithm
for episode in range(num_episodes):
    
    # random_map = generate_random_map(size=4, p=0.8)
    # env = gym.make("FrozenLake-v0", desc=random_map)
    env = gym.make("FrozenLake-v1")
    state = env.reset()

    done = False
    rewards_current_episode = 0

    for step in range (max_steps_per_episode):

        # Exploration / Exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)

# Calculate reward across all episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes / 1000)
count = 1000
print("*** AVG reward per 1000 episodes***\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

# Print Q table
print("\n\n *** Q-table ***\n")
print(q_table)
    

*** AVG reward per 1000 episodes***

1000 :  0.03300000000000002
2000 :  0.18100000000000013
3000 :  0.2660000000000002
4000 :  0.4260000000000003
5000 :  0.4910000000000004
6000 :  0.35500000000000026
7000 :  0.47900000000000037
8000 :  0.5280000000000004
9000 :  0.47600000000000037
10000 :  0.46500000000000036
11000 :  0.43700000000000033
12000 :  0.5530000000000004
13000 :  0.5950000000000004
14000 :  0.4920000000000004
15000 :  0.5500000000000004
16000 :  0.4280000000000003
17000 :  0.47200000000000036
18000 :  0.45200000000000035
19000 :  0.48100000000000037
20000 :  0.48000000000000037


 *** Q-table ***

[[0.07863591 0.04166855 0.04244633 0.04478868]
 [0.03000754 0.03557    0.02175198 0.05064043]
 [0.06534723 0.04009452 0.03940467 0.04019522]
 [0.0264728  0.02763057 0.03108342 0.03821474]
 [0.09803593 0.04802563 0.05373455 0.04585781]
 [0.         0.         0.         0.        ]
 [0.05062437 0.05387763 0.07814255 0.02321887]
 [0.         0.         0.         0.        ]
 [0.0

In [13]:
# random_map = generate_random_map(size=4, p=0.8)
# env = gym.make("FrozenLake-v0", desc=random_map)
env = gym.make("FrozenLake-v1")
for episode in range(1):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
            clear_output(wait=True)
            break
            
        state = new_state
        
env.close()

  (Right)
SFFF
FHFH
FFFH
HFFG
****You fell through a hole!****
